name: CD - Deploy with PM2

on:
  workflow_run:
    workflows: ["CI - Node.js"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            if [ ! -d "/var/www/myapp" ]; then
              mkdir -p /var/www/myapp
              cd /var/www/myapp
              git clone https://github.com/mdarifahammedreza/Ostad.git .
            else
              cd /var/www/myapp
              git pull origin main
            fi
            npm install --production
            pm2 reload ecosystem.config.js --update-env || pm2 start ecosystem.config.js
            pm2 save
